spring:
  application:
    name: api-gateway-zull
server:
  port: 80
zuul:
  sensitive-headers:
  routes:
    course:
      path: /course/**
      url: http://course-edge-service:8085/course/
    user:
      path: /user/**
      url: http://user-edge-service:8081/user/