spring:
  application:
    name: course-dubbo-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: jd_test
    password: Hzy12345678
    url: jdbc:mysql://116.196.81.166:3306/micro?characterEncoding=utf-8&useSSL=false
thrift:
  server:
    user:
      ip: user-service
      port: 9091
dubbo:
  scan:
    # have a bug : Using the default configuration 'base-package' will cause the service to start abnormally(0.2.0)
    basePackages: com.micrDemo.course.provider.service
  application:
    id: dubbo-provider-course
    name: dubbo-provider-course
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
  registry:
    id: my-registry
    address: N/A
course:
  service:
    version: 1.0.0
