spring:
  application:
    name: user-thrift-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/micro?characterEncoding=utf-8&useSSL=false
service:
  port: 9091