spring:
  application:
    name: user-thrift-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${mysql.username}
    password: ${mysql.password}
    url: jdbc:mysql://${mysql.address}:3306/micro?characterEncoding=utf-8&useSSL=false
service:
  port: 9091