apiVersion: v1
kind: Service
metadata:
  name: course-service
  labels:
    app: course-service
spec:
  ports:
    # service对内端口
  - name: course-dubbo-service-port
    port: 12345
    protocol: TCP
    # 容器端口
    targetPort: 12345
  - name: course-edge-service-port
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: course-service
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: course-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        # course-dubbo-service不对外提供服务，所以不用在上面ports定义映射到集群
      - name: course-dubbo-service
        image: msun96-cn-north-1.jcr.service.jdcloud.com/micro-service/course-dubbo-service
        ports:
        - containerPort: 12345
      - name: course-edge-service
        image: msun96-cn-north-1.jcr.service.jdcloud.com/micro-service/course-edge-service
        ports:
        - containerPort: 8085
      # 密匙
      imagePullSecrets:
      - name: secret

