apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
  - name: user-thrift-service-port
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: user-edge-service-port
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: user-service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-thrify-service
        image: msun96-cn-north-1.jcr.service.jdcloud.com/micro-service/user-thrift-service
        ports:
        - containerPort: 9091
      - name: user-edge-service
        image: msun96-cn-north-1.jcr.service.jdcloud.com/micro-service/user-edge-service
        ports:
        - containerPort: 8081
      # 密匙
      imagePullSecrets:
      - name: secret