spring:
  application:
    name: user-edge-service
  redis:
    host: ${redis.address}
    port: 6379
    password: ol4156tZpxagxn8W
server:
  port: 8081
thrift:
  server:
    user:
      ip: user-thrift-service
      port: 9091
    message:
      ip: message-service
      port: 9090
