spring:
  application:
    name: course-edge-service
server:
  port: 8085
management:
  port: 8086
dubbo:
  application:
    id: dubbo-consumer-course
    name: dubbo-consumer-course
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
course:
  service:
    version: 1.0.0